pipeline {
    agent any

    environment {
        NEXUS_REGISTRY      = "13.207.69.60:8081/repository/docker-hosted"
        SONARQUBE_SERVER    = "sonarqube-server"   // name configured in Jenkins > Manage Jenkins > System
        EKS_CLUSTER_NAME    = "microcloud-eks"
        SCANNERHOME         = tool 'SonarScanner'
        AWS_REGION          = "ap-south-1"
        IMAGE_TAG           = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/sakthiPrabha58/ecommerce-deployment.git'
            }
        }

       stage('Backend: Unit Tests') {
            steps {
                dir('app/backend') {
                    sh '''
                        if ! python3 -m venv --help >/dev/null 2>&1; then
                            sudo apt-get update && sudo apt-get install -y python3-venv
                        fi
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt pytest
                        pytest --junitxml=results.xml
                    '''
                }
            }
            post {
                always {
                    junit 'app/backend/results.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv("${SONARQUBE_SERVER}") {
                        sh """
                            echo "Running SonarQube analysis..."
                            ${SCANNER_HOME}/bin/sonar-scanner \
                              -Dsonar.projectKey=Microcloud \
                              -Dsonar.sources=app \
                              -Dsonar.python.version=3.12
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh """
                    docker build -t ${NEXUS_REGISTRY}/microcloud-backend:${IMAGE_TAG} ./app/backend
                    docker build -t ${NEXUS_REGISTRY}/microcloud-frontend:${IMAGE_TAG} ./app/frontend
                """
            }
        }

        stage('Push Images to Nexus') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-creds', usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                    sh """
                        echo "\$NEXUS_PASS" | docker login ${NEXUS_REGISTRY} -u "\$NEXUS_USER" --password-stdin
                        docker push ${NEXUS_REGISTRY}/microcloud-backend:${IMAGE_TAG}
                        docker push ${NEXUS_REGISTRY}/microcloud-frontend:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh """
                    aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME} --region ${AWS_REGION}

                    sed -i 's|<NEXUS_REGISTRY>/microcloud-backend:latest|${NEXUS_REGISTRY}/microcloud-backend:${IMAGE_TAG}|' k8s/backend-deployment.yaml
                    sed -i 's|<NEXUS_REGISTRY>/microcloud-frontend:latest|${NEXUS_REGISTRY}/microcloud-frontend:${IMAGE_TAG}|' k8s/frontend-deployment.yaml

                    kubectl apply -f k8s/namespace.yaml
                    kubectl apply -f k8s/backend-deployment.yaml
                    kubectl apply -f k8s/backend-service.yaml
                    kubectl apply -f k8s/frontend-deployment.yaml
                    kubectl apply -f k8s/frontend-service.yaml
                    kubectl apply -f k8s/ingress.yaml
                    kubectl apply -f k8s/hpa.yaml

                    kubectl rollout status deployment/backend -n microcloud
                    kubectl rollout status deployment/frontend -n microcloud
                """
            }
        }
    }

    post {
        success {
            echo "✅ CloudForge deployed successfully — build #${IMAGE_TAG}"
        }
        failure {
            echo "❌ Pipeline failed — check logs above"
        }
    }
}
